### ISSUE TITLE
Cloud should fly

### ISSUE THREAD

**Issue by jinglebiscuits** [ghouston/cloud#1]
Cloud is a jumping little animal right now. Change PlayerController.cs to get Cloud flying around instead.

**Comment by kutz4thesoul** [comment]
We have flight!

**Comment by jinglebiscuits** [comment]
Yeah!

**Comment by kutz4thesoul** [comment]
I didn't put any restrictions or limitations on flight because we haven't fully defined what that looks like.

**Comment by jinglebiscuits** [comment]
I added linear drag to the cloud and it looks pretty good now.
